import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Clock, Mail, MapPin, Phone } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHero } from "@/components/site-shell";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Jay Electronics | Sangli" }, { name: "description", content: "Contact Jay Electronics in Sangli for CCTV, networking, telecommunications, security and infrastructure requirements." },
  { property: "og:title", content: "Contact Jay Electronics" }, { property: "og:description", content: "Discuss your technology and infrastructure requirement with our team in Sangli." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() {
  const [sent,setSent]=useState(false);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSent(true);}
  return <><PageHero eyebrow="Contact us" title="Tell us what your site needs to achieve." description="Share your requirement and our team will help identify the right security, communication or infrastructure approach."/><section className="section"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><h2 className="text-2xl font-bold">Jay Electronics Private Limited</h2><p className="mt-3 leading-7 text-muted-foreground">For enquiries, project discussions and service requirements, contact our Sangli office.</p><div className="mt-8 space-y-3">{[
    {icon:MapPin,label:"Office",value:"College Corner, North Shivajinagar, Sangli 416416, Maharashtra",href:"https://maps.google.com/?q=College+Corner+North+Shivajinagar+Sangli+416416"},
    {icon:Phone,label:"Phone",value:"+91 94224 07175 · 0233-2326375",href:"tel:+919422407175"},
    {icon:Mail,label:"Email",value:"info@jayelectronics.co.in",href:"mailto:info@jayelectronics.co.in"},
    {icon:Clock,label:"Response",value:"Enquiries are reviewed during business hours",href:undefined},
  ].map(({icon:Icon,label,value,href})=><div key={label} className="grid grid-cols-[40px_1fr] gap-4 border-b border-border py-4"><span className="grid size-10 place-items-center bg-secondary"><Icon className="size-5 text-brand-blue"/></span><div><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p>{href?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} className="mt-1 block text-sm font-semibold hover:text-primary">{value}</a>:<p className="mt-1 text-sm font-semibold">{value}</p>}</div></div>)}</div></div><div className="border border-border bg-secondary p-6 sm:p-8">{sent?<div className="flex min-h-[430px] flex-col items-center justify-center text-center"><CheckCircle2 className="size-12 text-brand-blue"/><h2 className="mt-5 text-2xl font-bold">Thank you for your enquiry.</h2><p className="mt-3 max-w-md text-muted-foreground">Your details have been prepared for review. For an immediate response, please call +91 94224 07175.</p><Button className="mt-6" onClick={()=>setSent(false)}>Send another enquiry</Button></div>:<form onSubmit={submit}><h2 className="text-2xl font-bold">Project enquiry</h2><p className="mt-2 text-sm text-muted-foreground">Fields marked with * are required.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="form-label">Name *<Input required name="name" autoComplete="name"/></label><label className="form-label">Company<Input name="company" autoComplete="organization"/></label><label className="form-label">Email *<Input required name="email" type="email" autoComplete="email"/></label><label className="form-label">Phone *<Input required name="phone" type="tel" autoComplete="tel"/></label><label className="form-label sm:col-span-2">Service area<select required name="service" defaultValue="" className="mt-2 h-10 w-full border border-input bg-background px-3 text-sm"><option value="" disabled>Select a service</option><option>CCTV & Surveillance</option><option>Networking & Fibre</option><option>EPABX / IP-PBX</option><option>Audio Visual</option><option>Fire Security</option><option>Telecom Infrastructure</option><option>Office Automation</option><option>Solar Solutions</option></select></label><label className="form-label sm:col-span-2">Requirement *<Textarea required name="message" className="mt-2 min-h-32" placeholder="Tell us about your site and requirement"/></label></div><Button type="submit" size="lg" className="mt-6 w-full sm:w-auto">Submit enquiry</Button></form>}</div></div></section></>;
}