import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionHeading } from "@/components/site-shell";
import { projectCategories } from "@/lib/site-data";
import projectImage from "@/assets/gallery-1.jpg.asset.json";

export const Route = createFileRoute("/projects")({ head: () => ({ meta: [
  { title: "Technology Project Capabilities | Jay Electronics" }, { name: "description", content: "Explore Jay Electronics project capabilities across surveillance, government, healthcare, courts, networking, EPABX and AV." },
  { property: "og:title", content: "Project Capabilities | Jay Electronics" }, { property: "og:description", content: "Technology delivery capabilities across public, institutional and enterprise environments." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ProjectsPage });

function ProjectsPage() { return <><PageHero eyebrow="Project capabilities" title="Built around real environments and operational demands." description="Our experience spans public-sector, institutional, healthcare and enterprise technology environments."/><section className="section"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div className="lg:sticky lg:top-28 lg:self-start"><SectionHeading eyebrow="Delivery approach" title="From site conditions to a working system."/><p className="mt-5 leading-7 text-muted-foreground">Every project requires more than equipment. We consider coverage, connectivity, communication, installation constraints and future service needs as a coordinated whole.</p><img src={projectImage.url} alt="Digital security control environment" className="mt-8 aspect-[4/3] w-full object-cover"/></div><div className="grid gap-4 sm:grid-cols-2">{projectCategories.map(({title,category,description,icon:Icon},index)=><article key={title} className="border border-border p-6 transition hover:border-brand-blue"><div className="flex items-center justify-between"><Icon className="size-6 text-brand-blue"/><span className="text-xs font-bold text-muted-foreground">{String(index+1).padStart(2,"0")}</span></div><p className="mt-8 text-xs font-bold uppercase text-primary">{category}</p><h2 className="mt-2 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p></article>)}</div></div></section><section className="bg-brand-navy py-14 text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-4 sm:flex-row sm:items-center sm:px-6 lg:px-8"><div><h2 className="text-2xl font-bold">Have a project in planning?</h2><p className="mt-2 text-primary-foreground/65">Talk to us about the site, scope and technologies involved.</p></div><Button asChild><Link to="/contact">Start a conversation <ArrowRight/></Link></Button></div></section></>; }
