import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionHeading } from "@/components/site-shell";
import { capabilities } from "@/lib/site-data";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [
  { title: "CCTV, Networking & Telecom Services | Jay Electronics" }, { name: "description", content: "Explore CCTV, networking, fibre, EPABX, audio visual, fire security, office automation and telecom infrastructure services." },
  { property: "og:title", content: "Technology Services | Jay Electronics" }, { property: "og:description", content: "Integrated security, connectivity and communication solutions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ServicesPage });

function ServicesPage() { return <><PageHero eyebrow="Capabilities" title="Connected systems, engineered as one solution." description="From first site review to final commissioning, we coordinate the technologies your organisation relies on."/><section className="section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Service portfolio" title="Security, communication and infrastructure" description="Each engagement is shaped around the site, operating requirements and long-term serviceability."/><div className="mt-10 divide-y divide-border border-y border-border">{capabilities.map(({title,shortTitle,description,icon:Icon},index)=><article key={title} className="grid gap-5 py-7 md:grid-cols-[80px_1fr_1.2fr] md:items-center"><span className="text-xs font-bold text-muted-foreground">{String(index+1).padStart(2,"0")}</span><div className="flex items-center gap-4"><span className="grid size-11 shrink-0 place-items-center bg-secondary"><Icon className="size-5 text-brand-blue"/></span><h2 className="text-lg font-bold">{shortTitle}</h2></div><p className="text-sm leading-6 text-muted-foreground">{description}</p></article>)}</div></div></section><section className="bg-secondary py-14"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-4 sm:flex-row sm:items-center sm:px-6 lg:px-8"><div><h2 className="text-2xl font-bold">Planning a new system or upgrade?</h2><p className="mt-2 text-muted-foreground">Share your site and operational requirements with our team.</p></div><Button asChild size="lg"><Link to="/contact">Request a consultation <ArrowRight/></Link></Button></div></section></>; }
